
rpc_url: https://rpc.testnet.attra.me
ws_url: wss://rpc.testnet.attra.me

blockscout_public_ip: "explorer.testnet.attra.me"
blockscot_backend_port: 50102
swap_url: https://da.testnet.attra.me/
l1_explorer: https://sepolia.etherscan.io
bridge_info:
  l1_network_id: 11155111
  l2_network_id: 9701
